export const Screens = {
  SELECT_ADDED_ELEMENT_TYPE: "SELECT_ADDED_ELEMENT_TYPE",
  INTERFACE_FORM: "INTERFACE_FORM",
  COMPONENT_FORM: "COMPONENT_FORM",
  HELP: "HELP",
  HISTORY: "HISTORY",
  SEARCH: "SEARCH"
}
