export const ON_TICK_DONE = 'ON_TICK_DONE'
export const ENGINE_RUN = 'ENGINE_RUN'
export const ENGINE_PAUSE = 'ENGINE_PAUSE'
export const ENGINE_STEP = 'ENGINE_STEP'
export const ENGINE_RESET = 'ENGINE_RESET'
export const ENGINE_STATE = 'ENGINE_STATE'
